version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: jornada_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: jornada

    ports:
      - "5435:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: